name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to your first issue, please make sure it is not a duplicate of another issue and just make sure you are writing it in full detail. https://dontasktoask.com"
        pr-message: "Message that will be displayed on users' first pull request"
